family_messages/urls.py
from django.urls import path

from . import views

app_name = "family_messages"
urlpatterns = [
    path('', views.home, name='home'),
    path('message/<str:username>', views.view_message, name='view_message'),
    path('edit/<str:username>', views.edit_message, name='edit')
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

website/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

family_messages/models.py
from django.db import models
from django.contrib.auth.models import User

class Message(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text

users/models.py
from django.db import models

# Create your models here.

family_messages/forms.py
from django import forms

from .models import Message

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['text']

family_messages/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from .models import Message
from .forms import MessageForm

def home(request):
    users = User.objects.all()
    usernames = [user.username for user in users if not user.is_superuser]

    context = {"usernames": usernames}

    return render(request, "family_messages/home.html", context)

@login_required
def view_message(request, username):
    users = User.objects.all()
    usernames = [user.username for user in users if not user.is_superuser]

    user = users.get(username__exact=username)
    message = Message.objects.all().get(owner__exact=user)

    context = {"username": username, "usernames": usernames, "message": message}

    return render(request, "family_messages/message.html", context)

@login_required
def edit_message(request, username):
    users = User.objects.all()
    usernames = [user.username for user in users if not user.is_superuser]

    user = users.get(username__exact=username)
    message = Message.objects.all().get(owner__exact=user)

    if request.method != "POST":
        form = MessageForm(instance=message)

    else:
        form = MessageForm(instance=message, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("family_messages:home"))

    context = {"username": username, "usernames": usernames, "message": message, "form": form}
    
    return render(request, "family_messages/edit_message.html", context)

users/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

def login_view(request):    
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse("family_messages:home"))

    users = User.objects.all()
    usernames = [user.username for user in users if not user.is_superuser]
    
    form = AuthenticationForm()

    context = {"usernames": usernames, "form": form}

    return render(request, "users/login.html", context)

def logout_view(request):
    logout(request)
    
    return HttpResponseRedirect(reverse("family_messages:home"))

family_messages/templates/family_messages/base.html
{% load bootstrap4 %}

{% bootstrap_css %}
{% bootstrap_javascript jquery="full" %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Family Messages</title>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <a class="navbar-brand mx-2 my-1 my-sm-0" href="{% url 'family_messages:home' %}">
        Home
      </a>

      <div class="mr-auto">
        <button class="navbar-toggler mx-2" type="button" data-toggle="collapse" data-target="#navbarToggler">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>

      <div class="d-sm-none mx-2">
        {% if user.is_authenticated %}
        <form class="form-inline my-1 my-sm-0">
          <a class="btn btn-outline-success" href="{% url 'users:logout' %}" role="button">Logout</a>
        </form>
        {% else %}
        <a class="btn btn-outline-success align-self-end my-1 my-sm-0" href="{% url 'users:login' %}" role="button">Login</a>
        {% endif %}
      </div>
      
      <div class="collapse navbar-collapse" id="navbarToggler">
        <div class="navbar-nav mr-auto mx-3 my-1 my-sm-0">
          {% for username in usernames %}
          <a class="nav-item nav-link" href="{% url 'family_messages:view_message' username %}">{{ username }}</a>
          {% endfor %}
        </div>
      </div>
      
      <div class="d-none d-sm-block">
        {% if user.is_authenticated %}
        <form class="form-inline my-1 my-sm-0">
          <p class="text-white my-auto mx-4">Hello {{ user.username }}</p>
          <a class="btn btn-outline-success" href="{% url 'users:logout' %}" role="button">Logout</a>
        </form>
        {% else %}
        <a class="btn btn-outline-success my-1 my-sm-0" href="{% url 'users:login' %}" role="button">Login</a>
        {% endif %}
      </div>
    </nav>

    <main>
      <div class="container-fluid">
        {% block content %}{% endblock content %}
      </div>
    </main>

    <footer class="footer fixed-bottom py-3 bg-dark">
      <div class="text-left col-sm-12 mx-2">
        <a class="text-muted px-2" href="https://github.com/Hogwarts250/family_messages">Github</a>
        <a class="text-muted px-2" href="https://felixzhangblog.herokuapp.com">Blog</a>
      </div>
    </footer>

  </body>
</html>

family_messages/templates/family_messages/edit_message.html
{% extends "family_messages/base.html" %} {% load bootstrap4 %}

{% block content %}
<div class="justify-content-center m-5">
  <div class="d-flex flex-column mx-auto" style="max-width: 1000px;">
    <p class="h1 mr-auto my-auto">{{ username }}</p>

    <form action="{% url 'family_messages:edit' username %}" method="POST" class="form-group">
      {% csrf_token %}
      <div class="my-3">
        <textarea name="text" class="form-control" rows="12" placeholder="Text" required>{{ message }}</textarea>
      </div>

      <div class="my-3">
        <button type="submit" class="btn btn-outline-success">Save</button>
      </div>

      <input type="hidden" name="next" value="{% url 'family_messages:home' %}"/>
    </form>
  </div>
</div>
{% endblock content %}

family_messages/templates/family_messages/home.html
{% extends "family_messages/base.html" %}

{% block content %}
<div class="mx-auto" style="max-width: 1000px;">
  <div class="jumbotron jumbotron-fluid my-5">
    <p class="display-4 text-center">Family Message Board</p>
  </div>
</div>
{% endblock content %}

family_messages/templates/family_messages/message.html
{% extends "family_messages/base.html" %}

{% block content %}
<div class="m-5">
  <div class="d-flex flex-column mx-auto" style="max-width: 1000px;">
    <div class="d-flex flex-row justify-content-between">
      <h1 class="mb-0 text-left">{{ username }}</h1>

      {% if user.username == username %}
      <a href="{% url 'family_messages:edit' username %}" class="btn btn-outline-success align-self-center" role="button">Edit</a>
      {% endif %}
    </div>
    
    <p class="my-3">{{ message }}</p>
  </div>
</div>
{% endblock content %}

users/templates/users/login.html
{% extends "family_messages/base.html" %} {% load bootstrap4 %}

{% block content %}
<form method="POST" action="{% url 'users:login' %}" class="form mx-3 mt-5">
  {% csrf_token %}
  <div class="d-flex flex-column justify-content-center mx-auto" style="max-width: 600px;">
    <div class="fieldWrapper d-flex flex-row my-3">
      <div class="my-auto px-3" style="width: 100px;">
        <label for="{{ form.username.id_for_label }}" class="mb-0">Username</label>
      </div>
      <div class="flex-fill px-2">
        <input id="{{ form.username.id_for_label }}" type="text" name="username" class="form-control" placeholder="Username" autofocus="">
      </div>
    </div>

    <div class="fieldWrapper d-flex flex-row my-3">
      <div class="my-auto px-3" style="width: 100px;">
        <label for="{{ form.password.id_for_label }}" class="mb-0">Password</label>
      </div>
      <div class="flex-fill px-2">
        <input id="{{ form.password.id_for_label }}" type="password" name="password" class="form-control" placeholder="Password">
      </div>
    </div>

    <div class="d-flex flex-row ml-2 my-3 pl-2">
      <button type="submit" class="btn btn-outline-success">Submit</button>
    </div>   
  </div>

  <input type="hidden" name="next" value="{% url 'family_messages:home' %}"/>
</form>
{% endblock content %}